[package]
version = "0.1.0"
name = "recursive-arkworks-program"
edition = "2021"

[dependencies]
sp1-zkvm.workspace = true
borsh.workspace = true
types.workspace = true
jonas-groth16 = { path = "../jonas-groth16", features = ["sp1"] }
