[package]
version = "0.1.0"
name = "provable-program"
edition = "2021"

[dependencies]
sha2 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", tag = "patch-sha2-0.10.8-sp1-4.0.0" }
sp1-zkvm = "4.1.7"
borsh.workspace = true
