[package]
version = "0.1.0"
name = "smt-opening-proofs"
edition = "2021"

[dependencies]
sp1-zkvm.workspace = true
sp1-verifier.workspace = true
borsh.workspace = true
types.workspace = true
valence-coprocessor-core.workspace = true
valence-smt.workspace = true
